### ISSUE TITLE
Exception on no host raises an exception - URGENT

### ISSUE THREAD

**Issue by borpin** [openenergymonitor/emonhub#115]
Might be a Python3 thing @bwduncan - before it might have died quietly

https://github.com/openenergymonitor/emonhub/blob/da27a4aa68be47aafcb4ffe843ad09f9f450d481/src/emonhub_interfacer.py#L257

```
2020-07-02 16:09:09,461 WARNING  emoncmsorg emoncmsorg couldn't send to server: HTTPSConnectionPool(host='192.168.7.6', port=443): Max retries exceeded with url: /input/bulk.json?apikey=xxxxxxxx (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x75de4db0>: Failed to establish a new connection: [Errno 113] No route to host'))
2020-07-02 16:09:09,463 WARNING  emoncmsorg Exception caught in emoncmsorg thread. Traceback (most recent call last):
  File "/opt/openenergymonitor/emonhub/src/emonhub_interfacer.py", line 32, in wrapper
    return f(*args)
  File "/opt/openenergymonitor/emonhub/src/emonhub_interfacer.py", line 127, in run
    self.action()
  File "/opt/openenergymonitor/emonhub/src/emonhub_interfacer.py", line 198, in action
    self.flush()
  File "/opt/openenergymonitor/emonhub/src/emonhub_interfacer.py", line 216, in flush
    if self._process_post(databuffer):
  File "/opt/openenergymonitor/emonhub/src/interfacers/EmonHubEmoncmsHTTPInterfacer.py", line 71, in _process_post
    reply = self._send_post(post_url, {'data': data_string, 'sentat': str(sentat)})
  File "/opt/openenergymonitor/emonhub/src/emonhub_interfacer.py", line 257, in _send_post
    return reply.text
UnboundLocalError: local variable 'reply' referenced before assignment
```

**Comment by bwduncan** [comment]
Yes, in the past it would have just printed the first line, easily missed and probably going to recover next time round.

The rest is a bug. The fix is in PR #116
