### ISSUE TITLE
Exception if no route to host python3 branch

### ISSUE THREAD

**Issue by borpin** [openenergymonitor/emonhub#89]
Hi @TrystanLea @bwduncan

I saw this error on no route to host.  I think it should just buffer the data

```
2020-02-29 17:12:47,546 WARNING  emoncm77   emoncm77 couldn't send to server: HTTPConnectionPool(host='192.168.7.77', port=80): Max retries exceeded with url: //input/bulk.json?apikey=26135609fde7afcacbc40c74ff968f4e (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb39d7650>: Failed to establish a new connection: [Errno 113] No route to host'))
2020-02-29 17:12:47,553 WARNING  emoncm77   Exception caught in emoncm77 thread. Traceback (most recent call last):
  File "/opt/openenergymonitor/emonhub/src/emonhub_interfacer.py", line 32, in wrapper
    return f(*args)
  File "/opt/openenergymonitor/emonhub/src/emonhub_interfacer.py", line 127, in run
    self.action()
  File "/opt/openenergymonitor/emonhub/src/emonhub_interfacer.py", line 198, in action
    self.flush()
  File "/opt/openenergymonitor/emonhub/src/emonhub_interfacer.py", line 216, in flush
    if self._process_post(databuffer):
  File "/opt/openenergymonitor/emonhub/src/interfacers/EmonHubEmoncmsHTTPInterfacer.py", line 71, in _process_post
    reply = self._send_post(post_url, {'data': data_string, 'sentat': str(sentat)})
  File "/opt/openenergymonitor/emonhub/src/emonhub_interfacer.py", line 257, in _send_post
    return reply.text
UnboundLocalError: local variable 'reply' referenced before assignment
```

**Comment by bwduncan** [comment]
I agree. The error handling is a bit weird. Errors seem to be handled "low down", as in each interface must predict all possible errors and do... something. In this case it looks like the higher up interfacer `flush` method is capable of handing any error, but only if it's reported by returning a false value. It should be able to cope with any unhandled exception and, as you say, buffer the data until its queue is full.

However, in this case the code is in fact wrong. It should not be trying to use an object which doesn't exist. Moving `return reply.text` inside the body of the `try` would suffice.
